export const appRoutes = {
  login: "/login",
  forgotPassword: "/recuperar-senha",
  dashboard: "/dashboard",
  sales: "/vendas",
  salesLeadDetail: "/vendas/:leadId",
  rents: "/locacoes",
  rentLeadDetail: "/locacoes/:leadId",
  visits: "/agenda/visitas",
  keys: "/chaves",
  contracts: "/contratos",
  contractDetail: "/contratos/:contractId",
  contractGenerator: "/contratos/gerador",
  owners: "/proprietarios",
  ownerDetail: "/proprietarios/:ownerId",
  tenants: "/locatarios",
  tenantDetail: "/locatarios/:tenantId",
  properties: "/imoveis",
  propertyDetail: "/imoveis/:propertyId",
  users: "/usuarios",
  settings: "/configuracoes",
  forbidden: "/403",
} as const;

